name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Stable Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          default: true
          components: clippy, rustfmt
          
      - name: Install Nightly Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2026-02-11
          components: miri, rust-src, rustfmt, clippy
      
      - name: Rust Cache
        uses: swatinem/rust-cache@v2
      
      - name: Check Formatting
        if: matrix.os == 'ubuntu-latest'
        run: cargo +stable fmt --all --check
      
      - name: Clippy
        if: matrix.os == 'ubuntu-latest'
        run: cargo +stable clippy --workspace --all-targets --all-features -- -D warnings
      
      - name: Run Tests
        run: RUST_BACKTRACE=1 cargo +stable test --workspace --lib --bins --tests --all-features -- --include-ignored --test-threads=1
      
      - name: Run Miri Tests
        run: rm -rf ~/.cache/miri target/miri && bash ./miri-test.sh
